blank_issues_enabled: false
contact_links:
  - name: '`fdgt` Bug Reports, Feature Requests, & Technical Support'
    url: https://github.com/fdgt-apis/api/issues/new/choose
    about: Please ask and answer questions here.
